languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Lowkey Blowfish"
# logo = "img/logo.png"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Blue Blowfish"
  image = "img/avatar.png"
  headline = "This is my very simple profile website with my links"
  bio = "A little bit about you"
   links = [
     { link = "https://nunocoracao.github.io/blowfish/" },
     { github = "https://github.com/nunocoracao/blowfish" },
     { x-twitter = "https://twitter.com/burufugu" }
   ]
